// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $Post_id_ from "./routes/Post/[id].tsx";
import * as $Post_create from "./routes/Post/create.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $search from "./routes/search.tsx";
import * as $PostList from "./islands/PostList.tsx";
import * as $Posts from "./islands/Posts.tsx";
import * as $SearchAndViewPosts from "./islands/SearchAndViewPosts.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/Post/[id].tsx": $Post_id_,
    "./routes/Post/create.tsx": $Post_create,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/search.tsx": $search,
  },
  islands: {
    "./islands/PostList.tsx": $PostList,
    "./islands/Posts.tsx": $Posts,
    "./islands/SearchAndViewPosts.tsx": $SearchAndViewPosts,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
